Repository Team-BomBomBom/Web-Client, pull requests merged in 2024-06, with the labels that each got.

#2 Feat: #1 회원가입 페이지 구현
  components/header/header-nav-menu.tsx
  components/header/header.tsx
  components/ui/button.tsx
  components/ui/dropdown-menu.tsx
  components/ui/input.tsx
  components/ui/navigation-menu.tsx
  components/ui/textarea.tsx
  components/users/signup/signup-form.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/users/signup/index.tsx
  public/next.svg
  public/user-icon.svg
  public/vercel.svg
Labels: ✨Feat

#4 ✨Feat: 로그인 페이지 및 본인 프로필 조회 api
  components/header/header.tsx
  components/ui/label.tsx
  lib/api/auth/login.ts
  lib/api/users/me.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/login.tsx
Labels: ✨Feat

#6 Refactor: #5 App Router 방식으로 전환
  README.md
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  app/users/signup/page.tsx
  components.json
  components/users/signup/signup-form.tsx
  lib/api/users/signup.ts
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  postcss.config.js
  postcss.config.mjs
  tailwind.config.js
  tsconfig.json
Labels: 🛠️Refactor

#12 Feat: #7 스터디 목록 페이지 구현
  .vscode/settings.json
  app/globals.css
  app/layout.tsx
  app/study/page.tsx
  components/icon/icon.tsx
  components/study/study-grid.tsx
  components/study/study-group.tsx
  components/study/study-pagination.tsx
  components/study/ui/pagination.tsx
  constants/study/study.ts
  lib/api/study/studies.ts
  types/paging.ts
  types/study/study.ts
Labels: ✨Feat

#13 Feat: #10 #11 스터디 가입 기능 및 유저 상태 관리 (Recoil사용)
  app/globals.css
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  app/study/page.tsx
  app/users/signup/page.tsx
  components/header/header.tsx
  components/header/user-profile-drop-down.tsx
  components/study/study-grid.tsx
  components/study/study-group.tsx
  components/study/study-join-dialog.tsx
  components/ui/dialog/dialog.tsx
  components/ui/dropdown/dropdown-menu.tsx
  lib/api/study/join.ts
  package-lock.json
  package.json
  recoil/recoilRootProvider.tsx
  recoil/userAtom.ts
  types/user/user.ts
Labels: ✨Feat

#15 Feat: #9 스터디 생성 모달 구현
  .vscode/settings.json
  app/login/page.tsx
  app/study/page.tsx
  components/header/header-nav-menu.tsx
  components/header/header.tsx
  components/header/user-profile-drop-down.tsx
  components/icon/icon.tsx
  components/study/difficulty-level-dialog.tsx
  components/study/pagination.tsx
  components/study/study-create-modal.tsx
  components/study/study-grid.tsx
  components/study/study-group.tsx
  components/study/study-join-dialog.tsx
  components/study/study-pagination.tsx
  components/study/tier.tsx
  components/ui/button/button.tsx
  components/ui/dialog/dialog.tsx
  components/ui/icon/icon.tsx
  components/ui/input/input.tsx
  components/ui/label/label.tsx
  components/ui/navigation/navigation-menu.tsx
  components/ui/radio/radio-group.tsx
  components/ui/select/select.tsx
  components/ui/textarea/textarea.tsx
  components/users/signup/signup-form.tsx
  constants/study/study.ts
  lib/api/study/create-algorithm-study.ts
  lib/api/study/create-book-study.ts
  lib/api/study/studies.ts
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
  types/study/register-study.ts
  types/study/tier.ts
Labels: ✨Feat, ⚡️Fix

#17 Feat: #BBB-65 커밋시 지라 이슈키 자동포함
  .github/hooks/prepare-commit-msg
  .github/pull_request_template.md
Labels: 🧹Chore, ✨Feat
