Repository Team-BomBomBom/Web-Client, pull requests merged in 2024-07, with the labels that each got.

#18 Feat: #14 서적 검색 모달 구현
  components/book/book-search-modal.tsx
  components/book/book-search-table.tsx
  components/study/study-create-modal.tsx
  components/ui/table/table.tsx
  lib/api/book/search.ts
  types/book/book-result.ts
  types/study/register-study.ts
Labels: ✨Feat

#16 Fix: #BBB-68 스터디 목록 무한 호출 오류 수정, Feat: #15 스터디 생성 시 검증 추가
  app/layout.tsx
  app/login/page.tsx
  app/study/page.tsx
  components/study/pagination.tsx
  components/study/study-create-modal.tsx
  components/study/study-grid.tsx
  components/study/study-group.tsx
  components/study/study-join-dialog.tsx
  components/study/study-pagination.tsx
  components/users/signup/signup-form.tsx
  lib/utils.ts
  types/study/register-study.ts
Labels: ✨Feat, ⚡️Fix

#23 Build: #BBB-94 CI 구축
  .eslintrc.json
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/next.yml
  .prettierrc.json
  app/page.tsx
  app/study/page.tsx
  components.json
  components/book/book-search-table.tsx
  components/ui/button/button.tsx
  components/ui/dialog/dialog.tsx
  components/ui/dropdown/dropdown-menu.tsx
  components/ui/label/label.tsx
  components/ui/navigation/navigation-menu.tsx
  components/ui/radio/radio-group.tsx
  components/ui/select/select.tsx
  components/ui/textarea/textarea.tsx
  lib/api/auth/login.ts
  lib/api/study/join.ts
  lib/api/users/me.ts
  package-lock.json
  package.json
  postcss.config.mjs
  recoil/recoilRootProvider.tsx
  recoil/userAtom.ts
  types/study/register-study.ts
  types/user/user.ts
Labels: ⚙️Build

#22 Feat: #BBB-101 스터디 목록에서 기술서적 스터디의 책 제목 확인 가능
  components/study/study-create-modal.tsx
  components/study/study-group.tsx
  types/study/study.ts
  types/user/user.ts
Labels: ✨Feat

#24 Fix: #BBB-115 서적 확장 검색이 정상적으로 작동되지 않는 문제
  components/book/book-search-table.tsx
  lib/api/book/search.ts
Labels: ⚡️Fix

#25 Fix: #BBB-116 스터디 생성 시 주차 수가 항상 1로만 요청되는 이슈
  components/study/study-create-modal.tsx
Labels: ⚡️Fix

#26 ✨Feat: StudyDashBoard 페이지 구현
  .vscode/settings.json
  app/study/[id]/page.tsx
  components.json
  components/book/book-search-modal.tsx
  components/study/dashboard/about.tsx
  components/study/dashboard/dashboard.tsx
  components/study/dashboard/row.tsx
  components/ui/avatar/avatar.tsx
  components/ui/icon/icon.tsx
  components/ui/spinner/spinner.tsx
  components/users/signup/signup-form.tsx
  lib/api/study/get-details.ts
  lib/api/study/get-round.ts
  package-lock.json
  package.json
  types/study/register-study.ts
  types/study/study-detail.ts
Labels: ✨Feat

#27 Feat: #BBB-14 알고리즘 문제 피드백 모달 구현
  app/study/[id]/page.tsx
  components/study/dashboard/dashboard.tsx
  components/study/dashboard/row.tsx
  components/study/feedback-dialog.tsx
  components/ui/checkbox/checkbox.tsx
  components/ui/icon/icon.tsx
  components/ui/label/label.tsx
  lib/api/algo/give-feedback.ts
  package-lock.json
  package.json
  types/algo/feedback.ts
  types/study/study-detail.ts
Labels: ✨Feat
